// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"
	model "goshop/internal/cart/model"

	mock "github.com/stretchr/testify/mock"
)

// CartRepository is an autogenerated mock type for the CartRepository type.
type CartRepository struct {
	mock.Mock
}

func (_m *CartRepository) GetOrCreateCart(ctx context.Context, userID string) (*model.Cart, error) {
	ret := _m.Called(ctx, userID)
	if fn, ok := ret.Get(0).(func(context.Context, string) (*model.Cart, error)); ok {
		return fn(ctx, userID)
	}

	var cart *model.Cart
	if ret.Get(0) != nil {
		cart = ret.Get(0).(*model.Cart)
	}
	return cart, ret.Error(1)
}

func (_m *CartRepository) AddProduct(ctx context.Context, userID, productID string, quantity uint) (*model.Cart, error) {
	ret := _m.Called(ctx, userID, productID, quantity)
	if fn, ok := ret.Get(0).(func(context.Context, string, string, uint) (*model.Cart, error)); ok {
		return fn(ctx, userID, productID, quantity)
	}

	var cart *model.Cart
	if ret.Get(0) != nil {
		cart = ret.Get(0).(*model.Cart)
	}
	return cart, ret.Error(1)
}

func (_m *CartRepository) RemoveProduct(ctx context.Context, userID, productID string) (*model.Cart, error) {
	ret := _m.Called(ctx, userID, productID)
	if fn, ok := ret.Get(0).(func(context.Context, string, string) (*model.Cart, error)); ok {
		return fn(ctx, userID, productID)
	}

	var cart *model.Cart
	if ret.Get(0) != nil {
		cart = ret.Get(0).(*model.Cart)
	}
	return cart, ret.Error(1)
}

// NewCartRepository creates a new CartRepository and verifies expectations at cleanup.
func NewCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartRepository {
	repository := &CartRepository{}
	repository.Mock.Test(t)
	t.Cleanup(func() { repository.AssertExpectations(t) })
	return repository
}
