// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	redis "goshop/pkg/redis"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IRedis is an autogenerated mock type for the IRedis type
type IRedis struct {
	mock.Mock
}

// Get provides a mock function with given fields: key, value
func (_m *IRedis) Get(key string, value interface{}) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, key
func (_m *IRedis) Exists(ctx context.Context, key string) (bool, error) {
	ret := _m.Called(ctx, key)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsConnected provides a mock function with given fields:
func (_m *IRedis) IsConnected() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Ping provides a mock function with given fields: ctx
func (_m *IRedis) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		return rf(ctx)
	}
	return ret.Error(0)
}

// IncrementWithExpiration provides a mock function with given fields: key, expiration
func (_m *IRedis) IncrementWithExpiration(key string, expiration time.Duration) (int64, error) {
	ret := _m.Called(key, expiration)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string, time.Duration) int64); ok {
		r0 = rf(key, expiration)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(key, expiration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// XAdd provides a mock function with given fields: ctx, stream, values
func (_m *IRedis) XAdd(ctx context.Context, stream string, values map[string]interface{}) (string, error) {
	ret := _m.Called(ctx, stream, values)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (string, error)); ok {
		return rf(ctx, stream, values)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) string); ok {
		r0 = rf(ctx, stream, values)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, stream, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// XGroupCreateMkStream provides a mock function with given fields: ctx, stream, group, start
func (_m *IRedis) XGroupCreateMkStream(ctx context.Context, stream string, group string, start string) error {
	ret := _m.Called(ctx, stream, group, start)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, stream, group, start)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// XReadGroup provides a mock function with given fields: ctx, group, consumer, stream, count, block
func (_m *IRedis) XReadGroup(ctx context.Context, group string, consumer string, stream string, count int64, block time.Duration) ([]redis.RedisStreamMessage, error) {
	ret := _m.Called(ctx, group, consumer, stream, count, block)

	var r0 []redis.RedisStreamMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, time.Duration) ([]redis.RedisStreamMessage, error)); ok {
		return rf(ctx, group, consumer, stream, count, block)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, time.Duration) []redis.RedisStreamMessage); ok {
		r0 = rf(ctx, group, consumer, stream, count, block)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]redis.RedisStreamMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64, time.Duration) error); ok {
		r1 = rf(ctx, group, consumer, stream, count, block)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// XAck provides a mock function with given fields: ctx, stream, group, ids
func (_m *IRedis) XAck(ctx context.Context, stream string, group string, ids ...string) error {
	_va := make([]interface{}, len(ids))
	for _i := range ids {
		_va[_i] = ids[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, stream, group)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...string) error); ok {
		r0 = rf(ctx, stream, group, ids...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// XAutoClaim provides a mock function with given fields: ctx, stream, group, consumer, start, minIdle, count
func (_m *IRedis) XAutoClaim(ctx context.Context, stream string, group string, consumer string, start string, minIdle time.Duration, count int64) ([]redis.RedisStreamMessage, string, error) {
	ret := _m.Called(ctx, stream, group, consumer, start, minIdle, count)

	var r0 []redis.RedisStreamMessage
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, time.Duration, int64) ([]redis.RedisStreamMessage, string, error)); ok {
		return rf(ctx, stream, group, consumer, start, minIdle, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, time.Duration, int64) []redis.RedisStreamMessage); ok {
		r0 = rf(ctx, stream, group, consumer, start, minIdle, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]redis.RedisStreamMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, time.Duration, int64) string); ok {
		r1 = rf(ctx, stream, group, consumer, start, minIdle, count)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, string, time.Duration, int64) error); ok {
		r2 = rf(ctx, stream, group, consumer, start, minIdle, count)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Keys provides a mock function with given fields: pattern
func (_m *IRedis) Keys(pattern string) ([]string, error) {
	ret := _m.Called(pattern)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(pattern)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: keys
func (_m *IRedis) Remove(keys ...string) error {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(keys...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemovePattern provides a mock function with given fields: pattern
func (_m *IRedis) RemovePattern(pattern string) error {
	ret := _m.Called(pattern)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pattern)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: key, value
func (_m *IRedis) Set(key string, value interface{}) error {
	ret := _m.Called(key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWithExpiration provides a mock function with given fields: key, value, expiration
func (_m *IRedis) SetWithExpiration(key string, value interface{}, expiration time.Duration) error {
	ret := _m.Called(key, value, expiration)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, time.Duration) error); ok {
		r0 = rf(key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetNXWithExpiration provides a mock function with given fields: key, value, expiration
func (_m *IRedis) SetNXWithExpiration(key string, value interface{}, expiration time.Duration) (bool, error) {
	ret := _m.Called(key, value, expiration)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, interface{}, time.Duration) bool); ok {
		r0 = rf(key, value, expiration)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, interface{}, time.Duration) error); ok {
		r1 = rf(key, value, expiration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRedis creates a new instance of IRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRedis {
	mock := &IRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
